// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestKSK;

#nullable disable

namespace TestKSK.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230627185323_UpdateMoneyUnit")]
    partial class UpdateMoneyUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestKSK.Data.Beverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VendingMachineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendingMachineId");

                    b.ToTable("Beverage", (string)null);
                });

            modelBuilder.Entity("TestKSK.Data.MoneyUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Denomination")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("VendingMachineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendingMachineId");

                    b.ToTable("MoneyUnit", (string)null);
                });

            modelBuilder.Entity("TestKSK.Data.VendingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("UserBalance")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("VendingMachine", (string)null);
                });

            modelBuilder.Entity("TestKSK.Data.Beverage", b =>
                {
                    b.HasOne("TestKSK.Data.VendingMachine", "VendingMachine")
                        .WithMany("Beverages")
                        .HasForeignKey("VendingMachineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("VendingMachine");
                });

            modelBuilder.Entity("TestKSK.Data.MoneyUnit", b =>
                {
                    b.HasOne("TestKSK.Data.VendingMachine", "VendingMachine")
                        .WithMany("MoneyUnits")
                        .HasForeignKey("VendingMachineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("VendingMachine");
                });

            modelBuilder.Entity("TestKSK.Data.VendingMachine", b =>
                {
                    b.Navigation("Beverages");

                    b.Navigation("MoneyUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
